export const EVENTS = {
  JOIN_ROOM: 'join_room',
  LEAVE_ROOM: 'leave_room',
  ROOM_UPDATED: 'room_updated',
  PLAYER_JOINED: 'player_joined',
  PLAYER_LEFT: 'player_left',
  GAME_STARTED: 'game_started',
  NEXT_TRACK: 'next_track',
  TRACK_STARTED: 'track_started',
  GAME_ENDED: 'game_ended',
  BUZZ: 'buzz',
  BUZZ_RECEIVED: 'buzz_received',
  BUZZ_DENIED: 'buzz_denied',
  GRANT_POINT: 'grant_point',
  DENY_POINT: 'deny_point',
  PAUSE_AUDIO: 'pause_audio',
  RESUME_AUDIO: 'resume_audio',
  ROUND_ENDED: 'round_ended',
  SCORES_UPDATED: 'scores_updated',
  TIMER_START: 'timer_start',
  TIMER_TICK: 'timer_tick',
  TIMER_END: 'timer_end',
  TIMER_PAUSE: 'timer_pause',
  TIMER_RESET: 'timer_reset',
  STOP_GAME: 'stop_game',
}
